# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{weighted_average}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Seamus Abshere", "Andy Rossmeissl", "Ian Hough", "Matt Kling"]
  s.date = %q{2010-11-16}
  s.description = %q{Perform weighted averages, even across associations. Rails 3 only because it uses ARel.}
  s.email = %q{seamus@abshere.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/weighted_average.rb",
     "test/helper.rb",
     "test/test_weighted_average.rb",
     "weighted_average.gemspec"
  ]
  s.homepage = %q{http://github.com/seamusabshere/weighted_average}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Perform weighted averages. Rails 3 only.}
  s.test_files = [
    "test/helper.rb",
     "test/test_weighted_average.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3"])
      s.add_runtime_dependency(%q<arel>, ["~> 2"])
      s.add_development_dependency(%q<cohort_scope>, [">= 0.0.2"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.3"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3"])
      s.add_dependency(%q<arel>, ["~> 2"])
      s.add_dependency(%q<cohort_scope>, [">= 0.0.2"])
      s.add_dependency(%q<shoulda>, [">= 2.10.3"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3"])
    s.add_dependency(%q<arel>, ["~> 2"])
    s.add_dependency(%q<cohort_scope>, [">= 0.0.2"])
    s.add_dependency(%q<shoulda>, [">= 2.10.3"])
  end
end

